import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component StartWindow inherits Window {
  title: "Chast";
  width: 800px;
  height: 600px;
  background: black;

  callback switch-to-join-window;
  callback switch-to-create-window;

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 10px;

    Row {
        Text {
          text: "Chast";
          horizontal-alignment: center;
          font-size: 48px;
          font-weight: 900;
        }
    }
    Row {
      VerticalBox {
        Button {
          text: "Create Room";
          clicked => { switch-to-create-window(); } 
        }
        Button {
          text: "Join Room";
          clicked => { switch-to-join-window(); }
        }
      }
    }
  }
}

export component JoinWindow inherits Window {
  width: 800px;
  height: 600px;
  background: black;

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 25px;

    Row {
        LineEdit {
          placeholder-text: "Enter a username";
          horizontal-alignment: center;
        }
    }
    Row {
        LineEdit {
          horizontal-alignment: center;
          placeholder-text: "Enter a room token";
        }
    }
    Row {
        Button {
          text: "Join";
        }
    }
  }
}

export component CreateWindow inherits Window {
  width: 800px;
  height: 600px;
  background: #313e50;

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 25px;

    Row {
        LineEdit {
          placeholder-text: "Enter a username";
          horizontal-alignment: center;
        }
    }
    Row {
        Button {
          text: "Create";
        }
    }
  }
}
