import { Button, VerticalBox, HorizontalBox, LineEdit, TextEdit } from "std-widgets.slint";

export component StartWindow inherits Window {
  title: "Chast";
  width: 800px;
  height: 600px;
  background: black;

  callback switch-to-join-window;
  callback switch-to-create-window;

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 10px;

    Row {
        Text {
          text: "Chast";
          horizontal-alignment: center;
          font-size: 48px;
          font-weight: 900;
        }
    }
    Row {
      VerticalBox {
        Button {
          text: "Create Room";
          clicked => { switch-to-create-window(); } 
        }
        Button {
          text: "Join Room";
          clicked => { switch-to-join-window(); }
        }
      }
    }
  }
}

export component JoinWindow inherits Window {
  width: 800px;
  height: 600px;
  background: black;

  callback switch-to-chat-window;
  in-out property<string> username: "";
  in-out property<string> token: "";

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 25px;

    Row {
        LineEdit {
          text: username;
          placeholder-text: "Enter a username";
          horizontal-alignment: center;
          edited(text) => {
            text = username;
          }
        }
    }
    Row {
        LineEdit {
          text: token;
          horizontal-alignment: center;
          placeholder-text: "Enter a room token";
          edited(text) => {
            text = token;
          }
        }
    }
    Row {
        Button {
          text: "Join";
          clicked => { switch-to-chat-window(); }
        }
    }
  }
}

export component CreateWindow inherits Window {
  width: 800px;
  height: 600px;
  background: black;

  callback switch-to-chat-window;
  in-out property<string> username: "";

  GridLayout {
    padding-left: 300px;
    padding-right: 300px;
    padding-top: 250px;
    padding-bottom: 250px;
    spacing: 25px;

    Row {
        LineEdit {
          text = username;
          placeholder-text: "Enter a username";
          horizontal-alignment: center;
          edited(text) => {
            text = username;
          }
        }
    }
    Row {
        Button {
          text: "Create";
          clicked => { switch-to-chat-window(); }
        }
    }
  }
}

export component ChatWindow inherits Window {
  width: 800px;
  height: 600px;
  background: black;

  GridLayout {
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 10px;
    padding-bottom: 10px;
    spacing: 25px;

    Row {
        TextEdit {
          placeholder-text: "Message";
          horizontal-alignment: center;
        }
    }
    Row {
        Button {
          text: "Send";
        }
    }
  }
}
